# Dapr Secret Store Component - Local Development
# For production, use Azure Key Vault or Kubernetes Secrets
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: saga-secrets
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "./dapr/secrets.json"
  - name: nestedSeparator
    value: ":"
scopes:
  - saga-orchestrator
  - organization-service
  - debt-service
  - payment-service
  - notification-service
---
# Production - Azure Key Vault
# Provides secure, centralized secret management
# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: saga-secrets
# spec:
#   type: secretstores.azure.keyvault
#   version: v1
#   metadata:
#   - name: vaultName
#     value: "<your-keyvault-name>"
#   - name: azureTenantId
#     value: "<your-tenant-id>"
#   - name: azureClientId
#     value: "<your-client-id>"
#   - name: azureClientSecret
#     value: "<your-client-secret>"
# scopes:
#   - saga-orchestrator
#   - organization-service
#   - debt-service
#   - payment-service
#   - notification-service
